apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-2
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - https://github.com/multi-tenant-example-org/tenant-2
  roles:
  - name: guest
    description: "guest role"
  - name: developer
    description: "developer role"
  - name: operator
    description: "operator role"
